
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-07
owner: ucsb-cs156-f25
repo_name: team02-f25-07
pull_requests: [{"author":{"id":"MDQ6VXNlcjUxOTAxMTQ3","is_bot":false,"login":"MatthewMandell","name":""},"headRefName":"HelpRequestEdit","number":126,"title":"Help request edit","url":"https://github.com/ucsb-cs156-f25/team02-f25-07/pull/126"},{"author":{"id":"MDQ6VXNlcjUxOTAxMTQ3","is_bot":false,"login":"MatthewMandell","name":""},"headRefName":"HelpRequestIndex","number":125,"title":"Help request index","url":"https://github.com/ucsb-cs156-f25/team02-f25-07/pull/125"},{"author":{"id":"MDQ6VXNlcjUxOTAxMTQ3","is_bot":false,"login":"MatthewMandell","name":""},"headRefName":"HelpRequestCreatePage","number":124,"title":"Help request create page","url":"https://github.com/ucsb-cs156-f25/team02-f25-07/pull/124"},{"author":{"id":"MDQ6VXNlcjUxOTAxMTQ3","is_bot":false,"login":"MatthewMandell","name":""},"headRefName":"HelpRequestCopyPlaceholders","number":121,"title":"Help request copy placeholders","url":"https://github.com/ucsb-cs156-f25/team02-f25-07/pull/121"},{"author":{"id":"MDQ6VXNlcjUxOTAxMTQ3","is_bot":false,"login":"MatthewMandell","name":""},"headRefName":"helpRequestTable","number":120,"title":"Help request table","url":"https://github.com/ucsb-cs156-f25/team02-f25-07/pull/120"},{"author":{"id":"MDQ6VXNlcjUxOTAxMTQ3","is_bot":false,"login":"MatthewMandell","name":""},"headRefName":"HelpRequestForm","number":111,"title":"Help request form","url":"https://github.com/ucsb-cs156-f25/team02-f25-07/pull/111"},{"author":{"id":"U_kgDOCVJ10Q","is_bot":false,"login":"ArmanSajjadian","name":""},"headRefName":"as-edit","number":107,"title":"As edit","url":"https://github.com/ucsb-cs156-f25/team02-f25-07/pull/107"},{"author":{"id":"MDQ6VXNlcjUxOTAxMTQ3","is_bot":false,"login":"MatthewMandell","name":""},"headRefName":"HelpRequestFixtures","number":102,"title":"Help request fixtures","url":"https://github.com/ucsb-cs156-f25/team02-f25-07/pull/102"},{"author":{"id":"MDQ6VXNlcjUxOTAxMTQ3","is_bot":false,"login":"MatthewMandell","name":""},"headRefName":"copyfilesHelpRequest","number":99,"title":"copied files","url":"https://github.com/ucsb-cs156-f25/team02-f25-07/pull/99"}]
